/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.x19990416.paas.application.datamanager;

import com.github.x19990416.mxpaas.common.utils.SpringContextHolder;
import com.github.x19990416.mxpaas.module.menu.service.MenuService;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.transaction.annotation.EnableTransactionManagement;

@EnableCaching
@SpringBootApplication(scanBasePackages = {"com.github.x19990416"})
@EnableTransactionManagement
@EnableJpaRepositories(basePackages={"com.github.x19990416"})
@EntityScan(basePackages = {"com.github.x19990416"})
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args).getBean(MenuService.class);
    }

    @Bean
    public SpringContextHolder springContextHolder() {
        return new SpringContextHolder();
    }
}