/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.x19990416.mxpaas.module.jdbc;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

    }
}
