/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.x19990416.paas.module.user;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
